### ISSUE TITLE
Unknown node type: option_list

### ISSUE THREAD

**Issue by flying-sheep** [vscode-restructuredtext/vscode-restructuredtext#273]
**Environment**
- [x] Extension version: 142.0.0
- [x] Visual Studio Code version: 1.52.1
- [x] Operating System version: Arch linux (rolling release)
- [x] Python version: 3.9.1
- [x] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments: N/A

**Expected behavior**
The extension ignores .txt files or successfully handles [option lists](https://docutils.sourceforge.io/docs/ref/doctree.html#option-list)

**Actual behavior**
When encountering [this file](https://github.com/substack/node-mkdirp/blob/f2003bbcffa80f8c9744579fabab1212fc84545a/bin/usage.txt), a request fails with

```pytb
NotImplementedError: Unknown node type: option_list at .../mkdirp/bin/usage.txt:9
```

**Detailed Steps to reproduce the problem**
1. Have the extension globally installed
2. Open a JS project with [mkdirp](https://www.npmjs.com/package/mkdirp) installed

**Comment by lextm** [comment]
Should have been fixed in 55ce12faf691b512f217624aa5e12f0bf019921b

**Comment by JOJ0** [comment]
I am getting a similar error about one of my txt files in a project:

![Screen Shot 2021-03-14 at 07 58 56](https://user-images.githubusercontent.com/2733783/111060240-a819ea00-849b-11eb-9c34-6f33a913028e.png)

The txt file contains this:
```
sage: disco [-h] [-v] [-o] {search,mix,suggest,import,setup} ...

the DiscoDOS CLI.


optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         increases output verbosity / shows what DiscoDOS is
                        doing under the hood (-v is INFO level, -vv is DEBUG
                        level).
  -o, --offline         DiscoDOS checks for connectivity to online services
                        (Discogs, MusicBrainz, AcousticBrainz) itself. This
                        option forces offline mode. A lot of options work in
                        on- and offline mode. Some behave differently,
                        depending on connection state.
  ```

**Comment by JOJ0** [comment]
Not sure if it was a good idea to post into a closed issue? It might not be noticed but didn't want to add another duplicate.

**Comment by flying-sheep** [comment]
People usually still get notified, but you need to keep in mind to follow up with a new issue if you don’t get a reply.

At least that’s my experience.

**Comment by ocket8888** [comment]
Still seeing this in the latest release

**Comment by lextm** [comment]
@ocket8888 What exactly was the error message you saw and for what kind of files?

This issue was closed because .txt files have been excluded.

**Comment by ocket8888** [comment]
it's a reStructuredText source file, error is:
```
otImplementedError: Unknown node type: option_list at /home/ocket8888/src/github.com/apache/trafficcontrol/docs/source/development/building.rst:50
```

You can see the source file in question here: https://raw.githubusercontent.com/apache/trafficcontrol/8c32ae28eedf55b1d4a63083d234f8548c7beec4/docs/source/development/building.rst

Option Lists are a real reStructuredText node: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#option-lists
