### ISSUE TITLE
[Bug]: Autocompletion fails

### ISSUE THREAD

**Issue by twodrops** [vscode-restructuredtext/vscode-restructuredtext#376]
### Expected behavior

I expected that all directives are listed

### Actual behavior

When ".." is typed in a rST file, an exception is thrown and no autocompletion takes place.

### Detailed steps

The steps are,

### Extension information

184.0.1

### Visual Studio Code information

1.65.1

### Esbonio LS Version

0.10.2

### Operating system information

Windows 10

### Python information

3.8

### Sphinx information

4.5.0

### Relevant log output

```shell
Failed to handle request 49 textDocument/completion partial_result_token=None work_done_token=None text_document=TextDocumentIdentifier(uri='file:///workspace/docs/xxxxxx.rst') position=10:2 context=CompletionContext(trigger_kind=<CompletionTriggerKind.TriggerCharacter: 2>, trigger_character='.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pygls/protocol.py", line 331, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/usr/local/lib/python3.8/dist-packages/pygls/protocol.py", line 260, in _execute_request
    method_name, method_type, msg_id, handler(params))
  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/__init__.py", line 208, in on_completion
    for item in feature.complete(context):
  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/directives.py", line 289, in complete
    return self.complete_directives(context)
  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/directives.py", line 350, in complete_directives
    detail=f"{directive.__module__}.{directive.__name__}",
AttributeError: 'DirectiveContainer' object has no attribute '__name__'
[Error - 4:21:53 PM] Request textDocument/completion failed.
  Message: AttributeError: 'DirectiveContainer' object has no attribute '__name__'
  Code: -32602 
{'traceback': ['  File "/usr/local/lib/python3.8/dist-packages/pygls/protocol.py", line 331, in _handle_request\n    self._execute_request(msg_id, handler, params)\n', '  File "/usr/local/lib/python3.8/dist-packages/pygls/protocol.py", line 260, in _execute_request\n    method_name, method_type, msg_id, handler(params))\n', '  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/__init__.py", line 208, in on_completion\n    for item in feature.complete(context):\n', '  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/directives.py", line 289, in complete\n    return self.complete_directives(context)\n', '  File "/usr/local/lib/python3.8/dist-packages/esbonio/lsp/directives.py", line 350, in complete_directives\n    detail=f"{directive.__module__}.{directive.__name__}",\n']}
```
```

**Comment by alcarney** [comment]
What Sphinx extensions are you using? 

It looks like `DirectiveContainer` is slightly different to what the language server is expecting a directive to look like

**Comment by twodrops** [comment]
We are using the following extensions:

```
        "augustocdias.tasks-shell-input",
        "bbenoist.doxygen",
        "davidbroetje.algorithm-mnemonics-vscode",
        "eamodio.gitlens",
        "Gruntfuggly.todo-tree",
        "kevinkyang.auto-comment-blocks",
        "manuth.markdown-converter",
        "ms-python.python",
        "ms-vscode.cmake-tools",
        "ms-vscode.cpptools",
        "tomoki1207.pdf",
        "twxs.cmake",
        "wengerk.highlight-bad-chars",
        "cschlosser.doxdocgen",
        "cheshirekow.cmake-format",
        "streetsidesoftware.code-spell-checker",
        "notskm.clang-tidy",
        "tht13.html-preview-vscode",
        "lextudio.restructuredtext@184.0.0",
        "trond-snekvik.simple-rst@1.5.2",
        "hediet.vscode-drawio",
        "fredericbonnet.cmake-test-adapter",
        "redhat.vscode-yaml",
        "jebbs.plantuml",
        "parasoft.vscode-cpptest",
        "njpwerner.autodocstring",
        "timonwong.shellcheck"
```

**Comment by twodrops** [comment]
My bad. You had clearly mentioned "Sphinx" Extensions above.
Here they are:

```    "sphinx.ext.autodoc",
    "sphinx.ext.autosectionlabel",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.needs",
    "sphinxcontrib.plantuml",
    "breathe",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "myst_parser",
    "matplotlib.sphinxext.plot_directive",
    "sphinx.ext.duration",
    "sphinx.ext.graphviz",
    "sphinx.ext.todo",
    "sphinx_copybutton",
    "sphinx_click",
    "sphinx.ext.viewcode",```

**Comment by alcarney** [comment]
I think this is coming from the `breathe` extension which appears to wrap its directives to pass in some additional context.

I'll look to add a fix for this to esbonio as it should be easy enough to handle, however, it appears as though this issue may also be resolved in a relatively [recent release](https://github.com/michaeljones/breathe/releases/tag/v4.32.0) of breathe which [changes](https://github.com/michaeljones/breathe/pull/780/files#diff-aa3c1b8b4865dca9dd2c54b8535d1ea4b5ea656994e864ce25da60e736886caaL37) the way it registers its directives.

**Comment by twodrops** [comment]
@alcarney Thanks for finding this out. You are right. The problem is with `breathe`.
When I removed `breathe` it worked.
I had `breathe v4.31.1` in the project which I upgraded to the latest `4.33.0`. But it still failed.
Nevertheless, with `esbonio v0.10.3` it all works fine.

So we can close this issue.
Thanks for your quick help.

**Comment by lextm** [comment]
Will bump esbonio requirement to 0.10.3 in the upcoming release.
